# Generated by Django 4.2.7 on 2025-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genres", models.CharField(blank=True, max_length=200, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("director", models.CharField(blank=True, max_length=100, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("poster_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
