# Generated by Django 4.2.7 on 2025-08-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_alter_movie_title"),
    ]

    operations = []
