# Generated by Django 4.2.7 on 2025-08-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0004_remove_duplicates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="cast",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
    ]
