# Generated by Django 4.2.7 on 2025-08-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0005_remove_movie_cast_remove_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
